# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

includes:
  debug: .tasks/debug.yml
  git: .tasks/git.yml
  scans: .tasks/scans.yml

vars:
  SCAN_ROOTS:
    - repos
    - sparse-clones
    - worktrees

tasks:
  default:
    desc: Show machine info
    cmds:
      - task: debug:info

  status-all:
    desc: Show `git status` for all repos found in current path
    cmds:
      - task: git:status-all

  fetch-all:
    desc: Synchronize all git directories in the current path
    cmds:
      - task: git:fetch-all
 
  gitleaks-scan:
    desc: Run Gitleaks on all repositories
    cmds:
      - cmd: |
          for root in {{range .SCAN_ROOTS}}{{.}} {{end}}; do
            [ -d "$root" ] || continue

            # find all .git dirs up to depth 6, extract their parent paths
            find "$root" -mindepth 1 -maxdepth 6 -type d -name .git 2>/dev/null |
            while read -r gitdir; do
              repo="$(dirname "$gitdir")"
              echo "Scanning $repo with Gitleaks..."
              SCAN_TARGET="$repo" task scans:scan-gitleaks
            done
          done


  trufflehog-scan:
    desc: Run TruffleHog on all repositories
    cmds:
      - cmd: |
          for root in {{range .SCAN_ROOTS}}{{.}} {{end}}; do
            [ -d "$root" ] || continue

            find "$root" -mindepth 1 -maxdepth 6 -type d -name .git 2>/dev/null |
            while read -r gitdir; do
              repo="$(dirname "$gitdir")"
              echo "Scanning $repo with TruffleHog..."
              SCAN_TARGET="$repo" task scans:scan-trufflehog
            done
          done


  osv-scan:
    desc: Run OSV Scanner on all repositories
    cmds:
      - cmd: |
          for root in {{range .SCAN_ROOTS}}{{.}} {{end}}; do
            [ -d "$root" ] || continue

            find "$root" -mindepth 1 -maxdepth 6 -type d -name .git 2>/dev/null |
            while read -r gitdir; do
              repo="$(dirname "$gitdir")"
              echo "Scanning $repo with OSV..."
              SCAN_TARGET="$repo" task scans:scan-osv
            done
          done


  scan-all-repos:
    desc: Run all scanners on all repositories
    cmds:
      - cmd: |
          for root in {{range .SCAN_ROOTS}}{{.}} {{end}}; do
            [ -d "$root" ] || continue

            find "$root" -mindepth 1 -maxdepth 6 -type d -name .git 2>/dev/null |
            while read -r gitdir; do
              repo="$(dirname "$gitdir")"
              echo "Scanning $repo with all scanners..."
              SCAN_TARGET="$repo" task scans:scan-all
            done
          done

